formatter: "markdown table" # this is required

version: ""

header-from: ".config/.header.md"
footer-from: ".config/.footer.md"

recursive:
  enabled: false
  path: modules

sections:
  hide: [modules]
  show: []

content: |-
  {{ .Header }}
  
  {{ .Requirements }}

  {{ .Inputs }}

  {{ .Outputs }}

  {{ .Footer }}

output:
  file: README.md
  mode: replace
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->

output-values:
  enabled: false
  from: ""

sort:
  enabled: true
  by: required

settings:
  anchor: true
  color: true
  default: true
  description: false
  escape: false
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true